# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_auto_20160618_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
